# Generated by Django 4.2.16 on 2024-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todo",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
